use std::fs;
use std::io::Write;

use super::utils;

/// Metadata for one static asset that will be embedded in the generated code.
pub struct AssetGen {
    pub const_prefix: String,
    pub url_paths: Vec<String>,
    pub status_code: u16,
}

/// All the data needed by the code generator.
pub struct CodegenCtx {
    pub out_dir: String,
    pub gzip_dir: String,
    pub br_dir: String,
    pub build_version: String,
    pub assets: Vec<AssetGen>,
    pub asset_header_indices: Vec<usize>,
    pub header_sets: Vec<Vec<(String, String)>>,
    pub version_header_idx: usize,
    pub version_len: usize,
    pub not_found_header_idx: usize,
    pub not_found_const_prefix: Option<String>,
    pub files: Vec<String>,
    pub has_404: bool,
    pub use_uncompressed: Vec<bool>,
    pub use_brotli: Vec<bool>,
    pub version_use_uncompressed: bool,
    pub version_use_brotli: bool,
    pub uncompressed_lengths: Vec<usize>,
    pub version_uncompressed_len: usize,
}

/// Generate the `generated.rs` file with all embedded assets, TLS config, routing, etc.
pub fn generate(ctx: &CodegenCtx) {
    let generated_path = format!("{}/generated.rs", ctx.out_dir);
    let mut g = fs::File::create(&generated_path).expect("failed to create generated.rs");

    writeln!(g, "// Auto-generated by build.rs — DO NOT EDIT").unwrap();
    writeln!(g).unwrap();


    // ── Build version ──
    write_build_version(&mut g, &ctx.build_version);

    // ── TLS config ──
    write_tls_config(&mut g);

    // ── Asset constants ──
    write_asset_constants(&mut g, ctx);

    // ── Version asset ──
    write_version_asset(&mut g, ctx);

    // ── 404 fallback asset (only when no real 404.html exists) ──
    write_not_found_asset(&mut g, ctx);

    // ── Static header slices ──
    write_static_header_slices(&mut g, &ctx.header_sets);

    // ── Asset struct ──
    write_asset_struct(&mut g);

    // ── Static Asset instances ──
    write_asset_instances(&mut g, ctx);

    // ── ALL_ASSETS slice ──
    write_all_assets_slice(&mut g, ctx);

    // ── Routing function ──
    write_routing_function(&mut g, ctx);

    println!("cargo:rerun-if-changed=../public/");
}

fn write_build_version(g: &mut fs::File, build_version: &str) {
    writeln!(
        g,
        "/// Build fingerprint — changes whenever any file in public/ changes."
    )
    .unwrap();
    writeln!(
        g,
        "/// Used by the inline version-check script injected into every HTML page."
    )
    .unwrap();
    writeln!(g, "pub const BUILD_VERSION: &str = \"{build_version}\";").unwrap();
    writeln!(g).unwrap();
}

fn write_tls_config(g: &mut fs::File) {
    writeln!(
        g,
        "// ── TLS certificate (embedded at build time) ──────────────"
    )
    .unwrap();
    writeln!(
        g,
        "const CERT_DER: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/cert.der\"));"
    )
    .unwrap();
    writeln!(
        g,
        "const KEY_DER: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/key.der\"));"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(
        g,
        "/// Build a rustls ServerConfig with the embedded certificate and key."
    )
    .unwrap();
    writeln!(g, "/// ALPN is set to prefer h2, falling back to http/1.1.").unwrap();
    writeln!(
        g,
        "pub fn build_tls_config() -> std::sync::Arc<rustls::ServerConfig> {{"
    )
    .unwrap();
    writeln!(
        g,
        "    let cert_chain = vec![rustls::pki_types::CertificateDer::from(CERT_DER.to_vec())];"
    )
    .unwrap();
    writeln!(
        g,
        "    let key = rustls::pki_types::PrivateKeyDer::Pkcs8(rustls::pki_types::PrivatePkcs8KeyDer::from(KEY_DER.to_vec()));"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(g, "    let mut config = rustls::ServerConfig::builder()").unwrap();
    writeln!(g, "        .with_no_client_auth()").unwrap();
    writeln!(g, "        .with_single_cert(cert_chain, key)").unwrap();
    writeln!(
        g,
        "        .expect(\"invalid embedded TLS certificate or key\");"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(
        g,
        "    config.alpn_protocols = vec![b\"h2\".to_vec(), b\"http/1.1\".to_vec(), b\"h3\".to_vec()];"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(
        g,
        "    // Enable TLS 1.3 session resumption via stateless tickets."
    )
    .unwrap();
    writeln!(
        g,
        "    // Returning h2 clients skip the expensive certificate path and"
    )
    .unwrap();
    writeln!(
        g,
        "    // reconnect faster. The key is generated fresh at startup (a new"
    )
    .unwrap();
    writeln!(
        g,
        "    // process invalidates tickets from the previous run)."
    )
    .unwrap();
    writeln!(
        g,
        "    config.ticketer = rustls::crypto::ring::Ticketer::new()"
    )
    .unwrap();
    writeln!(
        g,
        "        .expect(\"failed to create TLS ticket encryptor\");"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(g).unwrap();
    writeln!(g, "    std::sync::Arc::new(config)").unwrap();
    writeln!(g, "}}").unwrap();
    writeln!(g).unwrap();
}

/// Write per-asset BODY/LEN/TYPE constants.
fn write_asset_constants(g: &mut fs::File, ctx: &CodegenCtx) {
    for (i, file) in ctx.files.iter().enumerate() {
        let suffix = if ctx.use_uncompressed[i] {
            ".gz.raw"
        } else if ctx.use_brotli[i] {
            ".br"
        } else {
            ".gz"
        };
        let embed_name = format!("{file}{suffix}");
        let embed_path = if ctx.use_brotli[i] {
            format!("{}/{}", ctx.br_dir, embed_name)
        } else {
            format!("{}/{}", ctx.gzip_dir, embed_name)
        };
        let content_length = fs::metadata(&embed_path)
            .expect("failed to stat body file")
            .len() as usize;
        let content_type = utils::mime_for_file(file);
        let const_prefix = utils::file_to_const(file);
        let uncompressed_len = ctx.uncompressed_lengths[i];
        let savings_pct = if uncompressed_len > 0 {
            (uncompressed_len - content_length) * 100 / uncompressed_len
        } else {
            0
        };

        writeln!(
            g,
            "// ── {file} ──────────────────────────────────────────────"
        )
        .unwrap();
        let include_dir = if ctx.use_brotli[i] { "brotli" } else { "gzip" };
        writeln!(
            g,
            "const {const_prefix}_BODY: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{include_dir}/{embed_name}\"));"
        )
        .unwrap();
        writeln!(g, "const {const_prefix}_LEN: usize = {content_length};").unwrap();
        writeln!(
            g,
            "const {const_prefix}_LEN_STR: &str = \"{content_length}\";"
        )
        .unwrap();
        writeln!(g, "const {const_prefix}_UNCOMPRESSED_LEN: usize = {uncompressed_len};").unwrap();
        writeln!(g, "const {const_prefix}_SAVINGS_PCT: usize = {savings_pct};").unwrap();
        writeln!(g, "const {const_prefix}_TYPE: &str = \"{content_type}\";").unwrap();
        writeln!(g).unwrap();
    }
}

fn write_version_asset(g: &mut fs::File, ctx: &CodegenCtx) {
    let embed_name = if ctx.version_use_uncompressed {
        "v.txt.gz.raw"
    } else if ctx.version_use_brotli {
        "v.txt.br"
    } else {
        "v.txt.gz"
    };
    let include_dir = if ctx.version_use_brotli { "brotli" } else { "gzip" };
    writeln!(
        g,
        "// ── /version (build fingerprint) ────────────────────────"
    )
    .unwrap();
    writeln!(
        g,
        "const VERSION_BODY: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{include_dir}/{embed_name}\"));"
    )
    .unwrap();
    writeln!(g, "const VERSION_LEN: usize = {};", ctx.version_len).unwrap();
    writeln!(g, "const VERSION_LEN_STR: &str = \"{}\";", ctx.version_len).unwrap();
    writeln!(
        g,
        "const VERSION_UNCOMPRESSED_LEN: usize = {};",
        ctx.version_uncompressed_len
    )
    .unwrap();
    let version_savings_pct = if ctx.version_uncompressed_len > 0 {
        (ctx.version_uncompressed_len - ctx.version_len) * 100 / ctx.version_uncompressed_len
    } else {
        0
    };
    writeln!(
        g,
        "const VERSION_SAVINGS_PCT: usize = {};",
        version_savings_pct
    )
    .unwrap();
    writeln!(
        g,
        "const VERSION_TYPE: &str = \"text/plain; charset=utf-8\";"
    )
    .unwrap();
    writeln!(g).unwrap();
}

fn write_not_found_asset(g: &mut fs::File, ctx: &CodegenCtx) {
    // Only generate a separate NOT_FOUND asset when there's no real 404.html.
    // When 404.html exists, it goes through the regular asset pipeline and is
    // referenced directly by the catch-all route.
    if ctx.has_404 {
        writeln!(g).unwrap();
        return;
    }

    let body: &[u8] = b"<h1>404 - Not Found</h1>";
    let len = body.len();
    let escaped_body = utils::escape_byte_string(body);

    writeln!(
        g,
        "// ── 404 Not Found (inline fallback) ────────────────────"
    )
    .unwrap();
    writeln!(g, "const NOT_FOUND_BODY: &[u8] = b\"{escaped_body}\";").unwrap();
    writeln!(g, "const NOT_FOUND_LEN: usize = {len};").unwrap();
    writeln!(g, "const NOT_FOUND_LEN_STR: &str = \"{len}\";").unwrap();
    writeln!(
        g,
        "const NOT_FOUND_UNCOMPRESSED_LEN: usize = {len};",
    )
    .unwrap();
    writeln!(
        g,
        "const NOT_FOUND_SAVINGS_PCT: usize = 0;",
    )
    .unwrap();
    writeln!(
        g,
        "const NOT_FOUND_TYPE: &str = \"text/html; charset=utf-8\";"
    )
    .unwrap();
    writeln!(g).unwrap();
}

/// Generate `const` header slices as `&[(&str, &str)]`.
/// We store string pairs rather than pre-built `HeaderName`/`HeaderValue` because
/// those types contain interior-mutable `Bytes` (atomic refcount) and Rust disallows
/// them in static/const items.
///
/// `HeaderName::from_static` / `HeaderValue::from_static` are `const fn` — validation
/// happens at compile time and the request-time call is just a pointer wrap, so the
/// overhead is negligible while avoiding the per-request `HeaderMap::clone()` allocation.
fn write_static_header_slices(g: &mut fs::File, header_sets: &[Vec<(String, String)>]) {
    for (i, headers) in header_sets.iter().enumerate() {
        writeln!(
            g,
            "const HEADERS_{i}: &[(&str, &str)] = &["
        )
        .unwrap();
        for (name, value) in headers {
            writeln!(
                g,
                "    (\"{name}\", \"{value}\"),"
            )
            .unwrap();
        }
        writeln!(g, "];").unwrap();
        writeln!(g).unwrap();
    }
}

fn write_asset_struct(g: &mut fs::File) {
    writeln!(
        g,
        "/// A pre-built static asset — every field is compile-time constant."
    )
    .unwrap();
    writeln!(g, "pub struct Asset {{").unwrap();
    writeln!(g, "    pub body: &'static [u8],").unwrap();
    writeln!(g, "    pub content_length: usize,").unwrap();
    writeln!(g, "    pub content_length_str: &'static str,").unwrap();
    writeln!(g, "    pub uncompressed_length: usize,").unwrap();
    writeln!(g, "    pub savings_pct: usize,").unwrap();
    writeln!(g, "    pub content_type: &'static str,").unwrap();
    writeln!(g, "    pub status_code: u16,").unwrap();
    writeln!(g, "    pub headers: &'static [(&'static str, &'static str)],").unwrap();
    writeln!(g, "}}").unwrap();
    writeln!(g).unwrap();
}

fn write_asset_instances(g: &mut fs::File, ctx: &CodegenCtx) {
    for (i, a) in ctx.assets.iter().enumerate() {
        let p = &a.const_prefix;
        let hi = ctx.asset_header_indices[i];
        let sc = a.status_code;
        writeln!(g, "static {p}_ASSET: Asset = Asset {{").unwrap();
        writeln!(g, "    body: {p}_BODY,").unwrap();
        writeln!(g, "    content_length: {p}_LEN,").unwrap();
        writeln!(g, "    content_length_str: {p}_LEN_STR,").unwrap();
        writeln!(g, "    uncompressed_length: {p}_UNCOMPRESSED_LEN,").unwrap();
        writeln!(g, "    savings_pct: {p}_SAVINGS_PCT,").unwrap();
        writeln!(g, "    content_type: {p}_TYPE,").unwrap();
        writeln!(g, "    status_code: {sc},").unwrap();
        writeln!(g, "    headers: HEADERS_{hi},").unwrap();
        writeln!(g, "}};").unwrap();
        writeln!(g).unwrap();
    }

    // version asset
    writeln!(g, "static VERSION_ASSET: Asset = Asset {{").unwrap();
    writeln!(g, "    body: VERSION_BODY,").unwrap();
    writeln!(g, "    content_length: VERSION_LEN,").unwrap();
    writeln!(g, "    content_length_str: VERSION_LEN_STR,").unwrap();
    writeln!(g, "    uncompressed_length: VERSION_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    savings_pct: VERSION_SAVINGS_PCT,").unwrap();
    writeln!(g, "    content_type: VERSION_TYPE,").unwrap();
    writeln!(g, "    status_code: 200,").unwrap();
    writeln!(g, "    headers: HEADERS_{},", ctx.version_header_idx).unwrap();
    writeln!(g, "}};").unwrap();
    writeln!(g).unwrap();

    // 404 fallback — only when no real 404.html exists
    if !ctx.has_404 {
        writeln!(g, "static NOT_FOUND_ASSET: Asset = Asset {{").unwrap();
        writeln!(g, "    body: NOT_FOUND_BODY,").unwrap();
        writeln!(g, "    content_length: NOT_FOUND_LEN,").unwrap();
        writeln!(g, "    content_length_str: NOT_FOUND_LEN_STR,").unwrap();
        writeln!(g, "    uncompressed_length: NOT_FOUND_UNCOMPRESSED_LEN,").unwrap();
        writeln!(g, "    savings_pct: NOT_FOUND_SAVINGS_PCT,").unwrap();
        writeln!(g, "    content_type: NOT_FOUND_TYPE,").unwrap();
        writeln!(g, "    status_code: 404,").unwrap();
        writeln!(g, "    headers: HEADERS_{},", ctx.not_found_header_idx).unwrap();
        writeln!(g, "}};").unwrap();
        writeln!(g).unwrap();
    }
}

fn write_all_assets_slice(g: &mut fs::File, ctx: &CodegenCtx) {
    writeln!(
        g,
        "/// All valid assets iterable at startup for one-time HeaderMap construction."
    )
    .unwrap();
    writeln!(g, "pub static ALL_ASSETS: &[&Asset] = &[").unwrap();
    for a in &ctx.assets {
        writeln!(g, "    &{}_ASSET,", a.const_prefix).unwrap();
    }
    writeln!(g, "    &VERSION_ASSET,").unwrap();
    if !ctx.has_404 {
        writeln!(g, "    &NOT_FOUND_ASSET,").unwrap();
    }
    writeln!(g, "];").unwrap();
    writeln!(g).unwrap();
}

fn write_routing_function(g: &mut fs::File, ctx: &CodegenCtx) {
    writeln!(g, "/// Route a URL path to its pre-built static asset.").unwrap();
    writeln!(g, "/// - `/`          → index.html").unwrap();
    writeln!(
        g,
        "/// - `/about`     → about.html  (extensionless ⇒ .html)"
    )
    .unwrap();
    writeln!(g, "/// Falls back to the embedded 404 page on no match.").unwrap();
    writeln!(g, "pub fn route(path: &str) -> &'static Asset {{").unwrap();
    writeln!(g, "    match path {{").unwrap();
    for a in &ctx.assets {
        for url in &a.url_paths {
            writeln!(g, "        \"{url}\" => &{p}_ASSET,", p = a.const_prefix).unwrap();
        }
    }
    writeln!(g, "        \"/v\" => &VERSION_ASSET,").unwrap();
    if let Some(ref p) = ctx.not_found_const_prefix {
        writeln!(g, "        _ => &{p}_ASSET,").unwrap();
    } else {
        writeln!(g, "        _ => &NOT_FOUND_ASSET,").unwrap();
    }
    writeln!(g, "    }}").unwrap();
    writeln!(g, "}}").unwrap();
    writeln!(g).unwrap();
}
