use std::fs;
use std::io::Write;

use super::utils;

/// Metadata for one static asset that will be embedded in the generated code.
pub struct AssetGen {
    pub const_prefix: String,
    pub url_paths: Vec<String>,
    pub status_code: u16,
}

/// All the data needed by the code generator.
pub struct CodegenCtx {
    pub out_dir: String,
    pub build_version: String,
    pub assets: Vec<AssetGen>,
    pub asset_header_indices: Vec<usize>,
    pub header_sets: Vec<Vec<(String, String)>>,
    pub version_header_idx: usize,
    pub not_found_header_idx: usize,
    pub not_found_file: Option<String>,
    pub files: Vec<String>,
    pub uncompressed_lengths: Vec<usize>,
    pub version_uncompressed_len: usize,
    pub gzip_lengths: Vec<usize>,
    pub brotli_lengths: Vec<usize>,
    pub zstd_lengths: Vec<usize>,
    pub version_gzip_len: usize,
    pub version_brotli_len: usize,
    pub version_zstd_len: usize,
}

/// Generate the `generated.rs` file with all embedded assets, TLS config, routing, etc.
pub fn generate(ctx: &CodegenCtx) {
    let generated_path = format!("{}/generated.rs", ctx.out_dir);
    let mut g = fs::File::create(&generated_path).expect("failed to create generated.rs");

    writeln!(g, "// Auto-generated by build.rs — DO NOT EDIT").unwrap();
    writeln!(g).unwrap();


    // ── Build version ──
    write_build_version(&mut g, &ctx.build_version);

    // ── TLS config ──
    write_tls_config(&mut g);

    // ── Asset constants ──
    write_asset_constants(&mut g, ctx);

    // ── Version asset ──
    write_version_asset(&mut g, ctx);

    // ── 404 fallback asset (only when no real 404.html exists) ──
    write_not_found_asset(&mut g, ctx);

    // ── Chrome DevTools well-known empty 404 ──
    write_chrome_devtools_asset(&mut g, ctx);



    // ── Asset struct ──
    write_asset_struct(&mut g);

    // ── Static Asset instances ──
    write_asset_instances(&mut g, ctx);

    // ── ALL_ASSETS slice ──
    write_all_assets_slice(&mut g, ctx);

    // ── Routing function ──
    write_routing_function(&mut g, ctx);

    println!("cargo:rerun-if-changed=../public/");
}

// ── write_build_version ──────────────────────────────────────────────

fn write_build_version(g: &mut fs::File, build_version: &str) {
    writeln!(
        g,
        "/// Build version hash, used as an ETag for conditional requests."
    )
    .unwrap();
    writeln!(
        g,
        "pub const BUILD_VERSION: &str = \"{build_version}\";"
    )
    .unwrap();
    writeln!(g).unwrap();
}

// ── write_tls_config ─────────────────────────────────────────────────

fn write_tls_config(g: &mut fs::File) {
    writeln!(
        g,
        "// ── TLS certificate (embedded at build time) ──────────────"
    )
    .unwrap();
    writeln!(
        g,
        "const CERT_DER: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/cert.der\"));"
    )
    .unwrap();
    writeln!(
        g,
        "const KEY_DER: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/key.der\"));"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(
        g,
        "/// Build a rustls ServerConfig with the embedded certificate and key."
    )
    .unwrap();
    writeln!(g, "/// ALPN is set to prefer h2, falling back to http/1.1.").unwrap();
    writeln!(
        g,
        "pub fn build_tls_config() -> std::sync::Arc<rustls::ServerConfig> {{"
    )
    .unwrap();
    writeln!(
        g,
        "    let cert_chain = vec![rustls::pki_types::CertificateDer::from(CERT_DER.to_vec())];"
    )
    .unwrap();
    writeln!(
        g,
        "    let key = rustls::pki_types::PrivateKeyDer::Pkcs8(rustls::pki_types::PrivatePkcs8KeyDer::from(KEY_DER.to_vec()));"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(g, "    let mut config = rustls::ServerConfig::builder()").unwrap();
    writeln!(g, "        .with_no_client_auth()").unwrap();
    writeln!(g, "        .with_single_cert(cert_chain, key)").unwrap();
    writeln!(
        g,
        "        .expect(\"invalid embedded TLS certificate or key\");"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(
        g,
        "    config.alpn_protocols = vec![b\"h2\".to_vec(), b\"http/1.1\".to_vec(), b\"h3\".to_vec()];"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(
        g,
        "    // Enable TLS 1.3 session resumption via stateless tickets."
    )
    .unwrap();
    writeln!(
        g,
        "    // Returning h2 clients skip the expensive certificate path and"
    )
    .unwrap();
    writeln!(
        g,
        "    // reconnect faster. The key is generated fresh at startup (a new"
    )
    .unwrap();
    writeln!(
        g,
        "    // process invalidates tickets from the previous run)."
    )
    .unwrap();
    writeln!(
        g,
        "    config.ticketer = rustls::crypto::ring::Ticketer::new()"
    )
    .unwrap();
    writeln!(
        g,
        "        .expect(\"failed to create TLS ticket encryptor\");"
    )
    .unwrap();
    writeln!(g).unwrap();
    writeln!(g).unwrap();
    writeln!(g, "    std::sync::Arc::new(config)").unwrap();
    writeln!(g, "}}").unwrap();
    writeln!(g).unwrap();
}

// ── write_asset_constants ────────────────────────────────────────────

fn write_asset_constants(g: &mut fs::File, ctx: &CodegenCtx) {
    for (i, file) in ctx.files.iter().enumerate() {
        let content_type = utils::mime_for_file(file);
        let const_prefix = utils::file_to_const(file);
        let uncompressed_len = ctx.uncompressed_lengths[i];
        let gzip_len = ctx.gzip_lengths[i];
        let brotli_len = ctx.brotli_lengths[i];
        let zstd_len = ctx.zstd_lengths[i];

        // Compute savings percentage using the best (smallest) encoding.
        let best_compressed = gzip_len.min(brotli_len).min(zstd_len).min(uncompressed_len);
        let savings_pct = if uncompressed_len > 0 {
            (uncompressed_len - best_compressed) * 100 / uncompressed_len
        } else {
            0
        };

        writeln!(
            g,
            "// ── {file} ──────────────────────────────────────────────"
        )
        .unwrap();

        // Uncompressed body (from the .gz.raw copy created by compress_to_gzip).
        writeln!(
            g,
            "const {const_prefix}_BODY: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/gzip/{file}.gz.raw\"));"
        )
        .unwrap();
        // Gzip-compressed body.
        writeln!(
            g,
            "const {const_prefix}_BODY_GZIP: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/gzip/{file}.gz\"));"
        )
        .unwrap();
        // Brotli-compressed body.
        writeln!(
            g,
            "const {const_prefix}_BODY_BROTLI: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/brotli/{file}.br\"));"
        )
        .unwrap();
        // Zstd-compressed body.
        writeln!(
            g,
            "const {const_prefix}_BODY_ZSTD: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/zstd/{file}.zst\"));"
        )
        .unwrap();

        writeln!(g, "const {const_prefix}_UNCOMPRESSED_LEN: usize = {uncompressed_len};").unwrap();
        writeln!(g, "const {const_prefix}_GZIP_LEN: usize = {gzip_len};").unwrap();
        writeln!(g, "const {const_prefix}_BROTLI_LEN: usize = {brotli_len};").unwrap();
        writeln!(g, "const {const_prefix}_ZSTD_LEN: usize = {zstd_len};").unwrap();
        writeln!(g, "const {const_prefix}_SAVINGS_PCT: usize = {savings_pct};").unwrap();
        writeln!(g, "const {const_prefix}_TYPE: &str = \"{content_type}\";").unwrap();
        writeln!(g, "const {const_prefix}_FILE: &str = \"{file}\";").unwrap();
        writeln!(g).unwrap();
    }
}

// ── write_version_asset ──────────────────────────────────────────────

fn write_version_asset(g: &mut fs::File, ctx: &CodegenCtx) {
    let version_savings_pct = if ctx.version_uncompressed_len > 0 {
        let best = ctx
            .version_gzip_len
            .min(ctx.version_brotli_len)
            .min(ctx.version_zstd_len)
            .min(ctx.version_uncompressed_len);
        (ctx.version_uncompressed_len - best) * 100 / ctx.version_uncompressed_len
    } else {
        0
    };

    writeln!(
        g,
        "// ── /version (build fingerprint) ────────────────────────"
    )
    .unwrap();

    // Uncompressed body.
    writeln!(
        g,
        "const VERSION_BODY: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/gzip/v.txt.gz.raw\"));"
    )
    .unwrap();
    // Gzip body.
    writeln!(
        g,
        "const VERSION_BODY_GZIP: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/gzip/v.txt.gz\"));"
    )
    .unwrap();
    // Brotli body.
    writeln!(
        g,
        "const VERSION_BODY_BROTLI: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/brotli/v.txt.br\"));"
    )
    .unwrap();
    // Zstd body.
    writeln!(
        g,
        "const VERSION_BODY_ZSTD: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/zstd/v.txt.zst\"));"
    )
    .unwrap();

    writeln!(
        g,
        "const VERSION_UNCOMPRESSED_LEN: usize = {};",
        ctx.version_uncompressed_len
    )
    .unwrap();
    writeln!(
        g,
        "const VERSION_GZIP_LEN: usize = {};",
        ctx.version_gzip_len
    )
    .unwrap();
    writeln!(
        g,
        "const VERSION_BROTLI_LEN: usize = {};",
        ctx.version_brotli_len
    )
    .unwrap();
    writeln!(
        g,
        "const VERSION_ZSTD_LEN: usize = {};",
        ctx.version_zstd_len
    )
    .unwrap();
    writeln!(
        g,
        "const VERSION_SAVINGS_PCT: usize = {};",
        version_savings_pct
    )
    .unwrap();
    writeln!(
        g,
        "const VERSION_TYPE: &str = \"text/plain; charset=utf-8\";"
    )
    .unwrap();
    writeln!(
        g,
        "const VERSION_FILE: &str = \"/v\";"
    )
    .unwrap();
    writeln!(g).unwrap();
}

// ── write_not_found_asset ─────────────────────────────────────────────

fn write_not_found_asset(g: &mut fs::File, ctx: &CodegenCtx) {
    if let Some(ref nf_file) = ctx.not_found_file {
        // Use the body from the configured 404 file (e.g. index.html or 404.html),
        // so the catch-all returns the same content as the file but with status 404.
        writeln!(
            g,
            "// ── 404 Not Found (from {nf_file}) ────────────────────"
        )
        .unwrap();
        writeln!(g, "const NOT_FOUND_BODY: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/gzip/{nf_file}.gz.raw\"));").unwrap();
        let len_field = format!("NOT_FOUND_UNCOMPRESSED_LEN: usize = NOT_FOUND_BODY.len();");
        writeln!(g, "const {len_field}").unwrap();
        // All encoding variants point to the same body — the file's body is already pre-compressed
        // variants, so serve uncompressed for simplicity.
        writeln!(g, "const NOT_FOUND_BODY_GZIP: &[u8] = NOT_FOUND_BODY;").unwrap();
        writeln!(g, "const NOT_FOUND_BODY_BROTLI: &[u8] = NOT_FOUND_BODY;").unwrap();
        writeln!(g, "const NOT_FOUND_BODY_ZSTD: &[u8] = NOT_FOUND_BODY;").unwrap();
        writeln!(g, "const NOT_FOUND_SAVINGS_PCT: usize = 0;").unwrap();
        writeln!(
            g,
            "const NOT_FOUND_TYPE: &str = \"{}\";",
            utils::mime_for_file(nf_file)
        )
        .unwrap();
        writeln!(g, "const NOT_FOUND_FILE: &str = \"{nf_file}\";").unwrap();
        writeln!(g).unwrap();
        return;
    }

    // No matching file — use the inline fallback.
    let body: &[u8] = b"<h1>404 - Not Found</h1>";
    let len = body.len();
    let escaped_body = utils::escape_byte_string(body);

    writeln!(
        g,
        "// ── 404 Not Found (inline fallback) ────────────────────"
    )
    .unwrap();
    // All encoding variants point to the same uncompressed body
    // since the inline 404 is tiny and not worth compressing.
    writeln!(g, "const NOT_FOUND_BODY: &[u8] = b\"{escaped_body}\";").unwrap();
    writeln!(g, "const NOT_FOUND_BODY_GZIP: &[u8] = b\"{escaped_body}\";").unwrap();
    writeln!(g, "const NOT_FOUND_BODY_BROTLI: &[u8] = b\"{escaped_body}\";").unwrap();
    writeln!(g, "const NOT_FOUND_BODY_ZSTD: &[u8] = b\"{escaped_body}\";").unwrap();
    writeln!(
        g,
        "const NOT_FOUND_UNCOMPRESSED_LEN: usize = {len};",
    )
    .unwrap();
    writeln!(
        g,
        "const NOT_FOUND_SAVINGS_PCT: usize = 0;",
    )
    .unwrap();
    writeln!(
        g,
        "const NOT_FOUND_TYPE: &str = \"text/html; charset=utf-8\";"
    )
    .unwrap();
    writeln!(
        g,
        "const NOT_FOUND_FILE: &str = \"[404 fallback]\";"
    )
    .unwrap();
    writeln!(g).unwrap();
}

fn write_chrome_devtools_asset(g: &mut fs::File, _ctx: &CodegenCtx) {
    // Always generate this special empty 404 regardless of NOT_FOUND_FILENAME.
    // Chrome probes this path for custom DevTools support; we respond with
    // a 404 (no content) to signal "not available" cleanly.
    writeln!(
        g,
        "// ── Chrome DevTools well-known (empty 404) ───────────"
    )
    .unwrap();
    writeln!(g, "const CHROME_DT_BODY: &[u8] = b\"\";").unwrap();
    writeln!(g, "const CHROME_DT_BODY_GZIP: &[u8] = b\"\";").unwrap();
    writeln!(g, "const CHROME_DT_BODY_BROTLI: &[u8] = b\"\";").unwrap();
    writeln!(g, "const CHROME_DT_BODY_ZSTD: &[u8] = b\"\";").unwrap();
    writeln!(g, "const CHROME_DT_UNCOMPRESSED_LEN: usize = 0;").unwrap();
    writeln!(g, "const CHROME_DT_SAVINGS_PCT: usize = 0;").unwrap();
    writeln!(g, "const CHROME_DT_TYPE: &str = \"application/json\";").unwrap();
    writeln!(g, "const CHROME_DT_FILE: &str = \"[chrome-devtools]\";").unwrap();
    writeln!(g).unwrap();
}


// ── write_asset_struct ───────────────────────────────────────────────

fn write_asset_struct(g: &mut fs::File) {
    writeln!(
        g,
        "/// A pre-built static asset — every field is compile-time constant."
    )
    .unwrap();
    writeln!(g, "///").unwrap();
    writeln!(
        g,
        "/// Holds all encoding variants so the server can perform runtime"
    )
    .unwrap();
    writeln!(
        g,
        "/// `Accept-Encoding` negotiation and serve the best match."
    )
    .unwrap();
    writeln!(g, "pub struct Asset {{").unwrap();
    writeln!(g, "    pub body: &'static [u8],").unwrap();
    writeln!(g, "    pub body_gzip: &'static [u8],").unwrap();
    writeln!(g, "    pub body_brotli: &'static [u8],").unwrap();
    writeln!(g, "    pub body_zstd: &'static [u8],").unwrap();
    writeln!(g, "    pub uncompressed_length: usize,").unwrap();
    writeln!(g, "    pub gzip_length: usize,").unwrap();
    writeln!(g, "    pub brotli_length: usize,").unwrap();
    writeln!(g, "    pub zstd_length: usize,").unwrap();
    writeln!(g, "    pub savings_pct: usize,").unwrap();
    writeln!(g, "    pub content_type: &'static str,").unwrap();
    writeln!(g, "    pub file: &'static str,").unwrap();
    writeln!(g, "    pub status_code: u16,").unwrap();
    writeln!(g, "    pub headers_identity: &'static [(&'static str, &'static str)],
    pub headers_gzip: &'static [(&'static str, &'static str)],
    pub headers_brotli: &'static [(&'static str, &'static str)],
    pub headers_zstd: &'static [(&'static str, &'static str)],").unwrap();
    writeln!(g, "}}").unwrap();
    writeln!(g).unwrap();
}

// ── write_per_encoding_header_arrays ──────────────────────────────────

fn write_per_encoding_header_arrays(
    g: &mut fs::File,
    const_prefix: &str,
    shared_headers: &[(String, String)],
    identity_len: usize,
    gzip_len: usize,
    brotli_len: usize,
    zstd_len: usize,
) {
    // Identity (no content-encoding header)
    writeln!(g, "const {const_prefix}_HEADERS_IDENTITY: &[(&str, &str)] = &[").unwrap();
    for (name, value) in shared_headers {
        writeln!(g, "    (\"{name}\", \"{value}\"),").unwrap();
    }
    writeln!(g, "    (\"content-length\", \"{identity_len}\"),").unwrap();
    writeln!(g, "];").unwrap();
    writeln!(g).unwrap();

    // Gzip
    writeln!(g, "const {const_prefix}_HEADERS_GZIP: &[(&str, &str)] = &[").unwrap();
    for (name, value) in shared_headers {
        writeln!(g, "    (\"{name}\", \"{value}\"),").unwrap();
    }
    writeln!(g, "    (\"content-length\", \"{gzip_len}\"),").unwrap();
    writeln!(g, "    (\"content-encoding\", \"gzip\"),").unwrap();
    writeln!(g, "];").unwrap();
    writeln!(g).unwrap();

    // Brotli
    writeln!(g, "const {const_prefix}_HEADERS_BROTLI: &[(&str, &str)] = &[").unwrap();
    for (name, value) in shared_headers {
        writeln!(g, "    (\"{name}\", \"{value}\"),").unwrap();
    }
    writeln!(g, "    (\"content-length\", \"{brotli_len}\"),").unwrap();
    writeln!(g, "    (\"content-encoding\", \"br\"),").unwrap();
    writeln!(g, "];").unwrap();
    writeln!(g).unwrap();

    // Zstd
    writeln!(g, "const {const_prefix}_HEADERS_ZSTD: &[(&str, &str)] = &[").unwrap();
    for (name, value) in shared_headers {
        writeln!(g, "    (\"{name}\", \"{value}\"),").unwrap();
    }
    writeln!(g, "    (\"content-length\", \"{zstd_len}\"),").unwrap();
    writeln!(g, "    (\"content-encoding\", \"zstd\"),").unwrap();
    writeln!(g, "];").unwrap();
    writeln!(g).unwrap();
}

// ── write_asset_instances ────────────────────────────────────────────

fn write_asset_instances(g: &mut fs::File, ctx: &CodegenCtx) {
    for (i, a) in ctx.assets.iter().enumerate() {
        let p = &a.const_prefix;
        let hi = ctx.asset_header_indices[i];
        let sc = a.status_code;

        write_per_encoding_header_arrays(
            g,
            p,
            &ctx.header_sets[hi],
            ctx.uncompressed_lengths[i],
            ctx.gzip_lengths[i],
            ctx.brotli_lengths[i],
            ctx.zstd_lengths[i],
        );

        writeln!(g, "static {p}_ASSET: Asset = Asset {{").unwrap();
        writeln!(g, "    body: {p}_BODY,").unwrap();
        writeln!(g, "    body_gzip: {p}_BODY_GZIP,").unwrap();
        writeln!(g, "    body_brotli: {p}_BODY_BROTLI,").unwrap();
        writeln!(g, "    body_zstd: {p}_BODY_ZSTD,").unwrap();
        writeln!(g, "    uncompressed_length: {p}_UNCOMPRESSED_LEN,").unwrap();
        writeln!(g, "    gzip_length: {p}_GZIP_LEN,").unwrap();
        writeln!(g, "    brotli_length: {p}_BROTLI_LEN,").unwrap();
        writeln!(g, "    zstd_length: {p}_ZSTD_LEN,").unwrap();
        writeln!(g, "    savings_pct: {p}_SAVINGS_PCT,").unwrap();
        writeln!(g, "    content_type: {p}_TYPE,").unwrap();
        writeln!(g, "    file: {p}_FILE,").unwrap();
        writeln!(g, "    status_code: {sc},").unwrap();
        writeln!(g, "    headers_identity: {p}_HEADERS_IDENTITY,").unwrap();
        writeln!(g, "    headers_gzip: {p}_HEADERS_GZIP,").unwrap();
        writeln!(g, "    headers_brotli: {p}_HEADERS_BROTLI,").unwrap();
        writeln!(g, "    headers_zstd: {p}_HEADERS_ZSTD,").unwrap();
        writeln!(g, "}};").unwrap();
        writeln!(g).unwrap();
    }

    // version asset
    write_per_encoding_header_arrays(
        g,
        "VERSION",
        &ctx.header_sets[ctx.version_header_idx],
        ctx.version_uncompressed_len,
        ctx.version_gzip_len,
        ctx.version_brotli_len,
        ctx.version_zstd_len,
    );

    writeln!(g, "static VERSION_ASSET: Asset = Asset {{").unwrap();
    writeln!(g, "    body: VERSION_BODY,").unwrap();
    writeln!(g, "    body_gzip: VERSION_BODY_GZIP,").unwrap();
    writeln!(g, "    body_brotli: VERSION_BODY_BROTLI,").unwrap();
    writeln!(g, "    body_zstd: VERSION_BODY_ZSTD,").unwrap();
    writeln!(g, "    uncompressed_length: VERSION_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    gzip_length: VERSION_GZIP_LEN,").unwrap();
    writeln!(g, "    brotli_length: VERSION_BROTLI_LEN,").unwrap();
    writeln!(g, "    zstd_length: VERSION_ZSTD_LEN,").unwrap();
    writeln!(g, "    savings_pct: VERSION_SAVINGS_PCT,").unwrap();
    writeln!(g, "    content_type: VERSION_TYPE,").unwrap();
    writeln!(g, "    file: VERSION_FILE,").unwrap();
    writeln!(g, "    status_code: 200,").unwrap();
    writeln!(g, "    headers_identity: VERSION_HEADERS_IDENTITY,").unwrap();
    writeln!(g, "    headers_gzip: VERSION_HEADERS_GZIP,").unwrap();
    writeln!(g, "    headers_brotli: VERSION_HEADERS_BROTLI,").unwrap();
    writeln!(g, "    headers_zstd: VERSION_HEADERS_ZSTD,").unwrap();
    writeln!(g, "}};").unwrap();
    writeln!(g).unwrap();

    // 404 fallback — always generated; body from NOT_FOUND_FILENAME when
    // available, otherwise inline HTML.
    if ctx.not_found_file.is_some() {
        // The not_found_header_idx was built for the NOT_FOUND file's headers.
        // Write per-encoding header arrays using the const length.
        let shared = &ctx.header_sets[ctx.not_found_header_idx];

        writeln!(g, "const NOT_FOUND_HEADERS_IDENTITY: &[(&str, &str)] = &[").unwrap();
        for (name, value) in shared {
            writeln!(g, "    (\"{name}\", \"{value}\"),").unwrap();
        }
        // content-length is not included — hyper computes it from the body.
        writeln!(g, "];").unwrap();
        writeln!(g).unwrap();

        // Gzip, Brotli, Zstd — use the pre-compressed variants from the file.
        // For simplicity, all encoding variants serve the uncompressed body since
        // the NOT_FOUND file is already processed through the compression pipeline.
        writeln!(g, "const NOT_FOUND_HEADERS_GZIP: &[(&str, &str)] = NOT_FOUND_HEADERS_IDENTITY;").unwrap();
        writeln!(g, "const NOT_FOUND_HEADERS_BROTLI: &[(&str, &str)] = NOT_FOUND_HEADERS_IDENTITY;").unwrap();
        writeln!(g, "const NOT_FOUND_HEADERS_ZSTD: &[(&str, &str)] = NOT_FOUND_HEADERS_IDENTITY;").unwrap();
        writeln!(g).unwrap();
    } else {
        let not_found_len: usize = 30; // "<h1>404 - Not Found</h1>"
        write_per_encoding_header_arrays(
            g,
            "NOT_FOUND",
            &ctx.header_sets[ctx.not_found_header_idx],
            not_found_len,
            not_found_len,
            not_found_len,
            not_found_len,
        );
    }

    writeln!(g, "static NOT_FOUND_ASSET: Asset = Asset {{").unwrap();
    writeln!(g, "    body: NOT_FOUND_BODY,").unwrap();
    writeln!(g, "    body_gzip: NOT_FOUND_BODY_GZIP,").unwrap();
    writeln!(g, "    body_brotli: NOT_FOUND_BODY_BROTLI,").unwrap();
    writeln!(g, "    body_zstd: NOT_FOUND_BODY_ZSTD,").unwrap();
    writeln!(g, "    uncompressed_length: NOT_FOUND_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    gzip_length: NOT_FOUND_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    brotli_length: NOT_FOUND_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    zstd_length: NOT_FOUND_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    savings_pct: NOT_FOUND_SAVINGS_PCT,").unwrap();
    writeln!(g, "    content_type: NOT_FOUND_TYPE,").unwrap();
    writeln!(g, "    file: NOT_FOUND_FILE,").unwrap();
    writeln!(g, "    status_code: 404,").unwrap();
    writeln!(g, "    headers_identity: NOT_FOUND_HEADERS_IDENTITY,").unwrap();
    writeln!(g, "    headers_gzip: NOT_FOUND_HEADERS_GZIP,").unwrap();
    writeln!(g, "    headers_brotli: NOT_FOUND_HEADERS_BROTLI,").unwrap();
    writeln!(g, "    headers_zstd: NOT_FOUND_HEADERS_ZSTD,").unwrap();
    writeln!(g, "}};").unwrap();
    writeln!(g).unwrap();

    // Chrome DevTools well-known empty 404 — always generated.
    // Simple headers: only content-type, content-length, and cache-control.
    let chrome_dt_headers: Vec<(String, String)> = vec![
        ("content-type".into(), "application/json".into()),
        ("content-length".into(), "0".into()),
        ("cache-control".into(), "no-cache, no-store, must-revalidate".into()),
    ];
    write_per_encoding_header_arrays(
        g,
        "CHROME_DT",
        &chrome_dt_headers,
        0,
        0,
        0,
        0,
    );

    writeln!(g, "static CHROME_DT_ASSET: Asset = Asset {{").unwrap();
    writeln!(g, "    body: CHROME_DT_BODY,").unwrap();
    writeln!(g, "    body_gzip: CHROME_DT_BODY_GZIP,").unwrap();
    writeln!(g, "    body_brotli: CHROME_DT_BODY_BROTLI,").unwrap();
    writeln!(g, "    body_zstd: CHROME_DT_BODY_ZSTD,").unwrap();
    writeln!(g, "    uncompressed_length: CHROME_DT_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    gzip_length: CHROME_DT_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    brotli_length: CHROME_DT_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    zstd_length: CHROME_DT_UNCOMPRESSED_LEN,").unwrap();
    writeln!(g, "    savings_pct: CHROME_DT_SAVINGS_PCT,").unwrap();
    writeln!(g, "    content_type: CHROME_DT_TYPE,").unwrap();
    writeln!(g, "    file: CHROME_DT_FILE,").unwrap();
    writeln!(g, "    status_code: 404,").unwrap();
    writeln!(g, "    headers_identity: CHROME_DT_HEADERS_IDENTITY,").unwrap();
    writeln!(g, "    headers_gzip: CHROME_DT_HEADERS_GZIP,").unwrap();
    writeln!(g, "    headers_brotli: CHROME_DT_HEADERS_BROTLI,").unwrap();
    writeln!(g, "    headers_zstd: CHROME_DT_HEADERS_ZSTD,").unwrap();
    writeln!(g, "}};").unwrap();
    writeln!(g).unwrap();
}

// ── write_all_assets_slice ───────────────────────────────────────────

fn write_all_assets_slice(g: &mut fs::File, ctx: &CodegenCtx) {
    writeln!(
        g,
        "/// All valid assets iterable at startup for one-time HeaderMap construction."
    )
    .unwrap();
    writeln!(g, "pub static ALL_ASSETS: &[&Asset] = &[").unwrap();
    for a in &ctx.assets {
        writeln!(g, "    &{}_ASSET,", a.const_prefix).unwrap();
    }
    writeln!(g, "    &VERSION_ASSET,").unwrap();
    writeln!(g, "    &CHROME_DT_ASSET,").unwrap();
    writeln!(g, "    &NOT_FOUND_ASSET,").unwrap();
    writeln!(g, "];").unwrap();
    writeln!(g).unwrap();
}

// ── write_routing_function ───────────────────────────────────────────

fn write_routing_function(g: &mut fs::File, ctx: &CodegenCtx) {
    writeln!(g, "/// Route a URL path to its pre-built static asset.").unwrap();
    writeln!(g, "/// - `/`          → index.html").unwrap();
    writeln!(
        g,
        "/// - `/about`     → about.html  (extensionless ⇒ .html)"
    )
    .unwrap();
    writeln!(g, "/// Falls back to the embedded 404 page on no match.").unwrap();
    writeln!(g, "pub fn route(path: &str) -> &'static Asset {{").unwrap();
    writeln!(g, "    match path {{").unwrap();
    for a in &ctx.assets {
        for url in &a.url_paths {
            writeln!(g, "        \"{url}\" => &{p}_ASSET,", p = a.const_prefix).unwrap();
        }
    }
    writeln!(g, "        \"/v\" => &VERSION_ASSET,").unwrap();
    writeln!(
        g,
        "        \"/.well-known/appspecific/com.chrome.devtools.json\" => &CHROME_DT_ASSET,"
    )
    .unwrap();
    writeln!(g, "        _ => &NOT_FOUND_ASSET,").unwrap();
    writeln!(g, "    }}").unwrap();
    writeln!(g, "}}").unwrap();
    writeln!(g).unwrap();
}
