use std::env;
use std::fs;
use std::io::Write;

/// Generate `config_constants.rs` in `OUT_DIR` with all server configuration
/// resolved from environment variables at build time. Values are baked into
/// the binary — no runtime env lookups, no config file I/O.
pub fn generate(out_dir: &str) {
    let config_path = format!("{out_dir}/config_constants.rs");
    let mut f = fs::File::create(&config_path).expect("failed to create config_constants.rs");

    let hostname = env::var("HOSTNAME").unwrap_or_else(|_| "localhost".into());
    let port: u16 = env::var("PORT")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(3000);

    let num_workers: usize = env::var("WORKERS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or_else(|| {
            std::thread::available_parallelism()
                .map(|n| n.get())
                .unwrap_or(4)
        });

    let max_connections: usize = env::var("MAX_CONNS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(1024);

    // A fixed-size handler pool trades memory for per-connection spawn
    // overhead. For a static file server the throughput gain from 512+
    // handlers is negligible; the floor of 64 alone was 8x what most
    // deployments need. We cap at 64 per worker (at most 8x64=512 tasks
    // total across the server) and floor at 8 to keep concurrency
    // reasonable on single-worker setups.
    let tcp_handlers_per_worker: usize = env::var("TCP_HANDLERS_PER_WORKER")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or_else(|| (max_connections / num_workers).max(8).min(64));

    let h3_handlers_per_connection: usize = env::var("H3_HANDLERS_PER_CONNECTION")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(4);

    let shutdown_timeout: u64 = env::var("SHUTDOWN_TIMEOUT_SECS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(3);

    writeln!(f, "// Auto-generated by build.rs — DO NOT EDIT").unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Server hostname — set via HOSTNAME at build time (default: localhost)."
    )
    .unwrap();
    writeln!(f, "pub(crate) const HOSTNAME: &str = \"{hostname}\";").unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Server port — set via PORT at build time (default: 3000)."
    )
    .unwrap();
    writeln!(f, "pub(crate) const PORT: u16 = {port};").unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Number of worker threads — set via WORKERS at build time"
    )
    .unwrap();
    writeln!(
        f,
        "/// (default: available_parallelism on the build machine, floor 4)."
    )
    .unwrap();
    writeln!(f, "pub(crate) const NUM_WORKERS: usize = {num_workers};").unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Maximum concurrent TCP connections — set via MAX_CONNS at build time (default: 4096).",
    )
    .unwrap();
    writeln!(
        f,
        "pub(crate) const MAX_CONNECTIONS: usize = {max_connections};"
    )
    .unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Number of TCP connection-handler tasks per worker — set via TCP_HANDLERS_PER_WORKER",
    )
    .unwrap();
    writeln!(
        f,
        "/// at build time (default: max(MAX_CONNECTIONS / NUM_WORKERS, 64))."
    )
    .unwrap();
    writeln!(
        f,
        "pub(crate) const TCP_HANDLERS_PER_WORKER: usize = {tcp_handlers_per_worker};"
    )
    .unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Number of request-handler tasks spawned per h3 connection — set via"
    )
    .unwrap();
    writeln!(
        f,
        "/// H3_HANDLERS_PER_CONNECTION at build time (default: 8)."
    )
    .unwrap();
    writeln!(
        f,
        "#[cfg(not(disable_http3))]"
    )
    .unwrap();
    writeln!(
        f,
        "pub(crate) const H3_HANDLERS_PER_CONNECTION: usize = {h3_handlers_per_connection};"
    )
    .unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Graceful shutdown timeout in seconds — set via SHUTDOWN_TIMEOUT_SECS"
    )
    .unwrap();
    writeln!(f, "/// at build time (default: 3).").unwrap();
    writeln!(
        f,
        "pub(crate) const SHUTDOWN_TIMEOUT_SECS: u64 = {shutdown_timeout};"
    )
    .unwrap();
    writeln!(f).unwrap();

    let h2_conn_window: u32 = env::var("H2_CONN_WINDOW")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(1 * 1024 * 1024);

    let h2_stream_window: u32 = env::var("H2_STREAM_WINDOW")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(1 * 1024 * 1024);

    let h2_max_frame_size: u32 = env::var("H2_MAX_FRAME_SIZE")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(16_384);

    let h2_max_send_buf: usize = env::var("H2_MAX_SEND_BUF")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(64 * 1024);

    writeln!(
        f,
        "/// HTTP/2 connection-level flow-control window in bytes — set via H2_CONN_WINDOW"
    )
    .unwrap();
    writeln!(f, "/// at build time (default: 16 MiB).").unwrap();
    writeln!(
        f,
        "pub(crate) const H2_CONN_WINDOW: u32 = {h2_conn_window};"
    )
    .unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// HTTP/2 per-stream flow-control window in bytes — set via H2_STREAM_WINDOW"
    )
    .unwrap();
    writeln!(f, "/// at build time (default: 4 MiB).").unwrap();
    writeln!(
        f,
        "pub(crate) const H2_STREAM_WINDOW: u32 = {h2_stream_window};"
    )
    .unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// HTTP/2 max frame size — set via H2_MAX_FRAME_SIZE at build time"
    )
    .unwrap();
    writeln!(f, "/// (default: 65535). Must be in range 16384..16777215.").unwrap();
    writeln!(
        f,
        "pub(crate) const H2_MAX_FRAME_SIZE: u32 = {h2_max_frame_size};"
    )
    .unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// HTTP/2 max per-stream send buffer in bytes — set via H2_MAX_SEND_BUF"
    )
    .unwrap();
    writeln!(f, "/// at build time (default: 256 KiB).").unwrap();
    writeln!(
        f,
        "pub(crate) const H2_MAX_SEND_BUF: usize = {h2_max_send_buf};"
    )
    .unwrap();
    writeln!(f).unwrap();

    let disable_logging: bool = env::var("DISABLE_LOGGING")
        .ok()
        .map(|s| s == "1" || s.to_lowercase() == "true")
        .unwrap_or(true);

    writeln!(
        f,
        "/// Disable all stderr logging — set via DISABLE_LOGGING at build time (default: true)."
    )
    .unwrap();
    writeln!(
        f,
        "/// When true, all request logging, error messages, and startup banners are compiled out."
    )
    .unwrap();
    writeln!(
        f,
        "/// Set DISABLE_LOGGING=false at build time to re-enable logging."
    )
    .unwrap();
    writeln!(f, "pub(crate) const DISABLE_LOGGING: bool = {disable_logging};").unwrap();
    writeln!(f).unwrap();

    // QUIC/HTTP3 adds substantial baseline RAM (~4-8 MB) from endpoint
    // configs, crypto material clones, and per-connection handler pools.
    // Static file servers rarely need it — disable by default.
    let disable_http3: bool = env::var("DISABLE_HTTP3")
        .ok()
        .map(|s| s == "1" || s.to_lowercase() == "true")
        .unwrap_or(true);

    writeln!(
        f,
        "/// Disable HTTP/3 (QUIC) support — set via DISABLE_HTTP3 at build time (default: true)."
    )
    .unwrap();
    writeln!(
        f,
        "/// When true, all QUIC/h3 code is compiled out, reducing binary size and RAM usage."
    )
    .unwrap();
    writeln!(f, "pub(crate) const DISABLE_HTTP3: bool = {disable_http3};").unwrap();
}
