use std::env;
use std::fs;
use std::io::Write;

/// Generate `config_constants.rs` in `OUT_DIR` with all server configuration
/// resolved from environment variables at build time. Values are baked into
/// the binary — no runtime env lookups, no config file I/O.
pub fn generate(out_dir: &str) {
    let config_path = format!("{out_dir}/config_constants.rs");
    let mut f = fs::File::create(&config_path).expect("failed to create config_constants.rs");

    let hostname = env::var("HOSTNAME").unwrap_or_else(|_| "localhost".into());
    let port: u16 = env::var("PORT")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(3000);

    let num_workers: usize = env::var("WORKERS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or_else(|| {
            std::thread::available_parallelism()
                .map(|n| n.get())
                .unwrap_or(4)
        });

    let max_connections: usize = env::var("MAX_CONNS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(4096);

    let tcp_handlers_per_worker: usize = env::var("TCP_HANDLERS_PER_WORKER")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or_else(|| (max_connections / num_workers).max(64));

    let shutdown_timeout: u64 = env::var("SHUTDOWN_TIMEOUT_SECS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(30);

    writeln!(f, "// Auto-generated by build.rs — DO NOT EDIT").unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Server hostname — set via HOSTNAME at build time (default: localhost)."
    )
    .unwrap();
    writeln!(f, "pub(crate) const HOSTNAME: &str = \"{hostname}\";").unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Server port — set via PORT at build time (default: 3000)."
    )
    .unwrap();
    writeln!(f, "pub(crate) const PORT: u16 = {port};").unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Number of worker threads — set via WORKERS at build time"
    )
    .unwrap();
    writeln!(
        f,
        "/// (default: available_parallelism on the build machine, floor 4)."
    )
    .unwrap();
    writeln!(f, "pub(crate) const NUM_WORKERS: usize = {num_workers};").unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Maximum concurrent TCP connections — set via MAX_CONNS at build time (default: 4096).",
    )
    .unwrap();
    writeln!(
        f,
        "pub(crate) const MAX_CONNECTIONS: usize = {max_connections};"
    )
    .unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Number of TCP connection-handler tasks per worker — set via TCP_HANDLERS_PER_WORKER",
    )
    .unwrap();
    writeln!(
        f,
        "/// at build time (default: max(MAX_CONNECTIONS / NUM_WORKERS, 64))."
    )
    .unwrap();
    writeln!(
        f,
        "pub(crate) const TCP_HANDLERS_PER_WORKER: usize = {tcp_handlers_per_worker};"
    )
    .unwrap();
    writeln!(f).unwrap();

    writeln!(
        f,
        "/// Graceful shutdown timeout in seconds — set via SHUTDOWN_TIMEOUT_SECS"
    )
    .unwrap();
    writeln!(f, "/// at build time (default: 30).").unwrap();
    writeln!(
        f,
        "pub(crate) const SHUTDOWN_TIMEOUT_SECS: u64 = {shutdown_timeout};"
    )
    .unwrap();
    writeln!(f).unwrap();

    let disable_sri: bool = env::var("DISABLE_SRI")
        .ok()
        .map(|s| s == "1" || s.to_lowercase() == "true")
        .unwrap_or(false);

    writeln!(
        f,
        "/// Disable Subresource Integrity (SRI) — set via DISABLE_SRI at build time (default: false)."
    )
    .unwrap();
    writeln!(
        f,
        "/// When true, content-hashed filenames, integrity attributes, and CSP hashes are omitted."
    )
    .unwrap();
    writeln!(f, "#[allow(dead_code)]").unwrap();
    writeln!(f, "pub(crate) const DISABLE_SRI: bool = {disable_sri};").unwrap();
    writeln!(f).unwrap();

    let disable_logging: bool = env::var("DISABLE_LOGGING")
        .ok()
        .map(|s| s == "1" || s.to_lowercase() == "true")
        .unwrap_or(true);

    writeln!(
        f,
        "/// Disable all stderr logging — set via DISABLE_LOGGING at build time (default: true)."
    )
    .unwrap();
    writeln!(
        f,
        "/// When true, all request logging, error messages, and startup banners are compiled out."
    )
    .unwrap();
    writeln!(
        f,
        "/// Set DISABLE_LOGGING=false at build time to re-enable logging."
    )
    .unwrap();
    writeln!(f, "pub(crate) const DISABLE_LOGGING: bool = {disable_logging};").unwrap();
}
